.TH PHOTO-UPLOAD "1" "September 2007" "photo-upload 0.2" "User Commands"

.SH NAME
photo-upload \- manual page for photo-upload 0.2

.SH SYNOPSIS
.B photo-upload
.RI [options]
.I images
.br

.SH DESCRIPTION
This manual page explains the
.B photo-upload
program. This program is simple uploader of photos to minilab.

.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-license\fR
Display program license.
.TP
\fB\-s\fR SERVICE_NAME, \fB\-\-service\fR=\fISERVICE_NAME\fR
Name of service to use. Use \fBphoto-upload \-l\fR to list currently 
available services.
.TP
\fB\-l\fR, \fB\-\-list\-services\fR
List available services.
.TP
\fB\-b\fR, \fB\-\-open\-browser\fR
Open order in browser after uploading.
.TP
\fB\-d\fR, \fB\-\-debug\fR
Show debugging output. This includes HTML files received from service.
.TP
\fB\-S\fR SESSION, \fB\-\-session\fR=\fISESSION\fR
Existing session to reuse (some services won't work
without existing session).

.SH EXAMPLES

.TP
Uploading all photos from /folder to default service and opening web browser to finish order:

photo-upload \-b /folder/*.jpg

.TP
Adding one image to existing session on ilikephoto.cz service:

photo-upload \-s ilikephoto.cz \-S f1721a19cc3c95218525a8429d48dab2 /tmp/Obraz024.jpg

.TP
Listing currently supported services:

photo-upload \-l

.SH LICENCE
This program is licensed under GNU/GPL version 2.

.SH BUGS
There are definitely many bugs, reporting to author is welcome. Please include
some useful information when sending bug reports (eg. exception you received
and debug output). Please submit your reports to <http://bugs.cihar.com/>.

.SH SEE ALSO
More information is available on program website:
<\fIhttp://cihar.com/software/photo-uploader/\fR>.

.SH AUTHOR
Michal Cihar <\fImichal@cihar.com\fR>

.SH COPYRIGHT
Copyright \(co 2007 Michal Cihar <\fImichal@cihar.com\fR>
