#!/bin/sh
# vim: expandtab sw=4 ts=4 sts=4:

# Usage: make-release [branch]

set -e

repo=photo-uploader

version=`python -c 'import phoupl; print phoupl.__version__' | tr -d '\n'`

srcdir=`pwd`


dotag=0
if [ "x$1" = "xbranch" ] ; then
    checkout=HEAD
    dotag=1
    # Pre release checks
    if grep -q '^200[0-9]-??-?? - ' ChangeLog ; then
        echo 'ChangeLog does not seem to be finalised, aborting!'
        exit 1
    fi
    shift
elif [ "x$1" = "x" ] ; then
    checkout=HEAD
else 
    checkout=$1
    version=$1
    shift
fi

tmp=`mktemp -dt $repo-build-XXXXXX`
cd $tmp
echo Working in $tmp
echo "Creating release $version from $checkout"
git clone $srcdir $repo-$version
cd $repo-$version

./setup.py sdist --formats=gztar,bztar,zip

mv dist/* ../

if [ $dotag -eq 1 ] ; then
    ./setup.py register
    # Tag the release
    cd $srcdir
    git tag -s -m "Tag release $version" "$version"
fi

echo "Release is in $tmp directory:"
ls -lh $tmp
chmod 644 $tmp/$repo-$version.*
